%
% CaMKIIs_der3.m
%
% This MATLAB function computes the third derivatives of the vector field
% defined in CaMKIIs_vf.m.
%
% der3_(n,i,j,k) is the third partial derivative of the n-th component
% of the vector field, taken with respect to the i-th, j-th and k-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on  8-Apr-2021 at 11:39
%
%
function der3_ = CaMKIIs_der3(t,x_,p_)
    a = 3.90264;
    b = 2.86972;
    s = 1.0E-5;
    CaM_Ca1    = x_(1);
    CaM_Ca2    = x_(2);
    CaM_Ca3    = x_(3);
    CaM_Ca4    = x_(4);
    PP2B_CaM   = x_(5);
    PP2B_CaM_Ca1 = x_(6);
    PP2B_CaM_Ca2 = x_(7);
    PP2B_CaM_Ca3 = x_(8);
    PP2B_CaM_Ca4 = x_(9);
    CaMKII_CaM = x_(10);
    CaMKII_CaM_Ca1 = x_(11);
    CaMKII_CaM_Ca2 = x_(12);
    CaMKII_CaM_Ca3 = x_(13);
    CaMKII_CaM_Ca4 = x_(14);
    pCaMKII_CaM_Ca4 = x_(15);
    pCaMKIIa   = x_(16);
    pCaMKII_CaM_Ca3 = x_(17);
    pCaMKII_CaM_Ca2 = x_(18);
    pCaMKII_CaM_Ca1 = x_(19);
    pCaMKII_CaM = x_(20);
    PP1__pCaMKIIa = x_(21);
    kf__CaM__Ca = p_(1);
    kf__CaM_Ca1__Ca = p_(2);
    kf__CaM_Ca2__Ca = p_(3);
    kf__CaM_Ca3__Ca = p_(4);
    kf__CaM__PP2B = p_(5);
    kf__CaM_Ca1__PP2B = p_(6);
    kf__CaM_Ca2__PP2B = p_(7);
    kf__CaM_Ca3__PP2B = p_(8);
    kf__CaM_Ca4__PP2B = p_(9);
    kf__PP2B_CaM__Ca = p_(10);
    kf__PP2B_CaM_Ca1__Ca = p_(11);
    kf__PP2B_CaM_Ca2__Ca = p_(12);
    kf__PP2B_CaM_Ca3__Ca = p_(13);
    KD__CaM_Ca3__Ca = p_(14);
    KD__CaM_Ca2__Ca = p_(15);
    KD__CaM_Ca1__Ca = p_(16);
    KD__CaM__Ca = p_(17);
    KD__CaM_Ca4__PP2B = p_(18);
    KD__PP2B_CaM_Ca3__Ca = p_(19);
    KD__PP2B_CaM_Ca2__Ca = p_(20);
    KD__PP2B_CaM_Ca1__Ca = p_(21);
    KD__PP2B_CaM__Ca = p_(22);
    kf__CaM__CaMKII = p_(23);
    kf__CaMKII_CaM_Ca3__Ca = p_(24);
    kf__CaMKII_CaM_Ca2__Ca = p_(25);
    kf__CaMKII_CaM_Ca1__Ca = p_(26);
    kf__CaMKII_CaM__Ca = p_(27);
    kf__CaM_Ca1__CaMKII = p_(28);
    kf__CaM_Ca2__CaMKII = p_(29);
    kf__CaM_Ca3__CaMKII = p_(30);
    kf__CaM_Ca4__CaMKII = p_(31);
    KD__CaM_Ca4__CaMKII = p_(32);
    KD__CaMKII_CaM_Ca3__Ca = p_(33);
    KD__CaMKII_CaM_Ca2__Ca = p_(34);
    KD__CaMKII_CaM_Ca1__Ca = p_(35);
    KD__CaMKII_CaM__Ca = p_(36);
    kf__pCaMKII_CaM_Ca3__Ca = p_(37);
    kf__CaM__pCaMKIIa = p_(38);
    kf__CaM_Ca1__pCaMKIIa = p_(39);
    kf__CaM_Ca2__pCaMKIIa = p_(40);
    kf__CaM_Ca3__pCaMKIIa = p_(41);
    kf__pCaMKII_CaM_Ca2__Ca = p_(42);
    kf__pCaMKII_CaM_Ca1__Ca = p_(43);
    kf__CaM_Ca4__pCaMKIIa = p_(44);
    kf__pCaMKII_CaM__Ca = p_(45);
    KD__pCaMKII_CaM_Ca3__Ca = p_(46);
    KD__pCaMKII_CaM_Ca2__Ca = p_(47);
    KD__pCaMKII_CaM_Ca1__Ca = p_(48);
    KD__pCaMKII_CaM__Ca = p_(49);
    KD__CaM_Ca4__pCaMKIIa = p_(50);
    kautMax    = p_(51);
    kf__PP1__pCaMKIIa = p_(52);
    kr__PP1__pCaMKIIa = p_(53);
    kcat__PP1__pCaMKIIa = p_(54);
    Ca_set     = p_(55);
    PP1_0      = p_(56);
    CaMKII_0   = p_(57);
    CaM_0      = p_(58);
    PP2B_0     = p_(59);

    der3_ = zeros(21,21,21,21);














    der3_(14,14,14,14) = -6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(14,14,14,15) = -4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+8*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(14,14,15,14) = der3_(14,14,14,15);
    der3_(14,15,14,14) = der3_(14,14,14,15);
    der3_(14,14,14,21) = 14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-8*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+10*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a;
    der3_(14,14,21,14) = der3_(14,14,14,21);
    der3_(14,21,14,14) = der3_(14,14,14,21);
    der3_(14,14,15,15) = -2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(14,15,15,14) = der3_(14,14,15,15);
    der3_(14,15,14,15) = der3_(14,14,15,15);
    der3_(14,14,15,21) = 14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+5*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a;
    der3_(14,14,21,15) = der3_(14,14,15,21);
    der3_(14,21,15,14) = der3_(14,14,15,21);
    der3_(14,15,14,21) = der3_(14,14,15,21);
    der3_(14,14,21,21) = -20*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(14,21,21,14) = der3_(14,14,21,21);
    der3_(14,21,14,21) = der3_(14,14,21,21);
    der3_(14,15,15,15) = -12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(14,15,15,21) = 14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(14,15,21,15) = der3_(14,15,15,21);
    der3_(14,21,15,15) = der3_(14,15,15,21);
    der3_(14,15,21,21) = -20*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(14,21,21,15) = der3_(14,15,21,21);
    der3_(14,21,15,21) = der3_(14,15,21,21);
    der3_(14,21,21,21) = 6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^5*(CaMKII_0+s-PP1__pCaMKIIa)^(-8)*a+36*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a;

    der3_(15,14,14,14) = 6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(15,14,14,15) = 4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-8*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(15,14,15,14) = der3_(15,14,14,15);
    der3_(15,15,14,14) = der3_(15,14,14,15);
    der3_(15,14,14,21) = -14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+8*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-10*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a;
    der3_(15,14,21,14) = der3_(15,14,14,21);
    der3_(15,21,14,14) = der3_(15,14,14,21);
    der3_(15,14,15,15) = 2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-2)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(15,15,15,14) = der3_(15,14,15,15);
    der3_(15,15,14,15) = der3_(15,14,15,15);
    der3_(15,14,15,21) = -14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a+16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-5*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a;
    der3_(15,14,21,15) = der3_(15,14,15,21);
    der3_(15,21,15,14) = der3_(15,14,15,21);
    der3_(15,15,14,21) = der3_(15,14,15,21);
    der3_(15,14,21,21) = 20*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+2*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a+6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(15,21,21,14) = der3_(15,14,21,21);
    der3_(15,21,14,21) = der3_(15,14,21,21);
    der3_(15,15,15,15) = 12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a;
    der3_(15,15,15,21) = -14*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a+4*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_0+s-PP1__pCaMKIIa)^(-3)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+16*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(15,15,21,15) = der3_(15,15,15,21);
    der3_(15,21,15,15) = der3_(15,15,15,21);
    der3_(15,15,21,21) = 20*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a-6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a+12*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-4)*a-24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a;
    der3_(15,21,21,15) = der3_(15,15,21,21);
    der3_(15,21,15,21) = der3_(15,15,21,21);
    der3_(15,21,21,21) = -6*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-4)*b^3*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^5*(CaMKII_0+s-PP1__pCaMKIIa)^(-8)*a-36*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-2)*b*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^3*(CaMKII_0+s-PP1__pCaMKIIa)^(-6)*a+24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-1)*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^2*(CaMKII_0+s-PP1__pCaMKIIa)^(-5)*a+24*(1+b*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)*(CaMKII_0+s-PP1__pCaMKIIa)^(-1))^(-3)*b^2*CaMKII_CaM_Ca4*kautMax*(CaMKII_CaM_Ca4+pCaMKII_CaM_Ca4)^4*(CaMKII_0+s-PP1__pCaMKIIa)^(-7)*a;







