/*
 *  CaMKIIs_gvf.h
 *
 *  GSL C prototype file for the functions defined in CaMKIIs_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on  2-Mar-2021 at 12:21
 */

int CaMKIIs_vf(double, const double [], double [], void *);
int CaMKIIs_jac(double, const double [], double *, double *, void *);
int CaMKIIs_jacp(double, const double [], double *, void *);
double CaMKIIs_MolCaPerMolCaM(double, const double [], void *);
double CaMKIIs_AutoCamkiiPercentage(double, const double [], void *);
double CaMKIIs_MolCaMPerMolPP2B(double, const double [], void *);
double CaMKIIs_ActivePP2BPercentage(double, const double [], void *);
