#
# HarmonicOscillator_demo.R
#
# R demonstration script that uses the vector field
# defined in HarmonicOscillator.R
#
# This file was generated by the program VFGEN, version: 2.6.0.dev1
# Generated on 20-Apr-2021 at 00:03
#

library(deSolve)

# Load the vector field definition and the jacobian.
source("HarmonicOscillator.R")


# --- Parameters ---
parameters = c(
    k = 0.5+dk,
    c = 0.0,
    F = 0.0
)

# --- Initial conditions ---
state = c(
    v = 0.0,
    y = 1.0
)


# --- Call the ODE solver ---
sol = ode(y = state, times = x, func = HarmonicOscillator, parms = parameters,
          jactype = "fullusr", jacfunc = HarmonicOscillator_jac,
          atol = 1e-8, rtol = 1e-6)

# --- Plot the solution ---
par(mfcol = c(2, 1))
tm <- sol[, "time"]
plot(tm, sol[, "v"], type = "l", col = "blue",
     xlab = "t", ylab = "v")
plot(tm, sol[, "y"], type = "l", col = "blue",
     xlab = "t", ylab = "y")
