#
# HarmonicOscillator.R
#
# R vector field functions for: HarmonicOscillator
#
# This file was generated by the program VFGEN, version: 2.6.0.dev1
# Generated on 20-Apr-2021 at 00:03
#


#
# HarmonicOscillator(t, state, parameters)
#
# The vector field function
#
HarmonicOscillator <- function(t, state, parameters) {
    v          <- state[1]
    y          <- state[2]
    k          <- parameters[1]
    c          <- parameters[2]
    F          <- parameters[3]

    vf_ <- vector(len = 2)
    vf_[1] = -v*c+F-k*y;
    vf_[2] = v;
    return(list(vf_))
}

#
# HarmonicOscillator_jac(t, state, parameters)
#
# The jacobian function
#
HarmonicOscillator_jac <- function(t, state, parameters) {
    v          <- state[1]
    y          <- state[2]
    k          <- parameters[1]
    c          <- parameters[2]
    F          <- parameters[3]
    jac_ = matrix(nrow = 2, ncol = 2)
    jac_[1,1] = -c
    jac_[1,2] = -k
    jac_[2,1] = 1
    jac_[2,2] = 0
    return(jac_)
}

