/*
 *  LinearSystem_gvf.h
 *
 *  GSL C prototype file for the functions defined in LinearSystem_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 26-Apr-2021 at 01:27
 */

int LinearSystem_vf(double, const double [], double [], void *);
int LinearSystem_jac(double, const double [], double *, double *, void *);
int LinearSystem_jacp(double, const double [], double *, void *);
