/*
 *  LinearSystem_gvf.c
 *
 *  GSL C file for the vector field named: LinearSystem
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 26-Apr-2021 at 16:47
 */

#include <math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_odeiv.h>

/*
 *  The vector field.
 */

int LinearSystem_vf(double t, const double y_[], double f_[], void *params)
{
    const double a11 = -6.0999999999999996e+00;
    const double a12 = 1.8999999999999999e+00;
    const double a13 = -1.8000000000000000e+00;
    const double a14 = -2.0000000000000001e-01;
    const double a15 = 9.0000000000000002e-01;
    const double a16 = -4.7999999999999998e+00;
    const double a22 = -2.8999999999999999e+00;
    const double a23 = 1.0;
    const double a24 = 2.9999999999999999e-01;
    const double a25 = 2.7000000000000002e+00;
    const double a26 = 9.0000000000000002e-01;
    const double a33 = -4.2999999999999998e+00;
    const double a34 = 1.2000000000000000e+00;
    const double a35 = -2.2000000000000002e+00;
    const double a36 = 1.3000000000000000e+00;
    const double a44 = -4.9000000000000004e+00;
    const double a45 = -6.9999999999999996e-01;
    const double a46 = -3.7000000000000002e+00;
    const double a55 = -6.4000000000000004e+00;
    const double a56 = 1.1000000000000001e+00;
    const double a66 = -1.0600000000000000e+01;
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];

    f_[0] =  a13*x3+a14*x4+a15*x5+a12*x2+u+x1*a11+(b1*b1)+a16*x6;
    f_[1] =  a23*x3+x5*a25+x1*a12+(b2*b2)+u+x4*a24+a22*x2+a26*x6;
    f_[2] =  x1*a13+(b3*b3)+a33*x3+x4*a34+a35*x5+u+a36*x6+a23*x2;
    f_[3] =  a24*x2+a34*x3+x4*a44+u+a46*x6+a14*x1+a45*x5+(b4*b4);
    f_[4] =  a45*x4+a56*x6+x1*a15+(b5*b5)+u+a35*x3+x2*a25+x5*a55;
    f_[5] =  x4*a46+a26*x2+a66*x6+u+a56*x5+x1*a16+(b6*b6)+a36*x3;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian.
 */

int LinearSystem_jac(double t, const double y_[], double *jac_, double *dfdt_, void *params)
{
    const double a11 = -6.0999999999999996e+00;
    const double a12 = 1.8999999999999999e+00;
    const double a13 = -1.8000000000000000e+00;
    const double a14 = -2.0000000000000001e-01;
    const double a15 = 9.0000000000000002e-01;
    const double a16 = -4.7999999999999998e+00;
    const double a22 = -2.8999999999999999e+00;
    const double a23 = 1.0;
    const double a24 = 2.9999999999999999e-01;
    const double a25 = 2.7000000000000002e+00;
    const double a26 = 9.0000000000000002e-01;
    const double a33 = -4.2999999999999998e+00;
    const double a34 = 1.2000000000000000e+00;
    const double a35 = -2.2000000000000002e+00;
    const double a36 = 1.3000000000000000e+00;
    const double a44 = -4.9000000000000004e+00;
    const double a45 = -6.9999999999999996e-01;
    const double a46 = -3.7000000000000002e+00;
    const double a55 = -6.4000000000000004e+00;
    const double a56 = 1.1000000000000001e+00;
    const double a66 = -1.0600000000000000e+01;
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];

    gsl_matrix_view dfdy_mat = gsl_matrix_view_array(jac_,6,6);
    gsl_matrix *m_ = &dfdy_mat.matrix;

    gsl_matrix_set(m_, 0, 0, a11);
    gsl_matrix_set(m_, 0, 1, a12);
    gsl_matrix_set(m_, 0, 2, a13);
    gsl_matrix_set(m_, 0, 3, a14);
    gsl_matrix_set(m_, 0, 4, a15);
    gsl_matrix_set(m_, 0, 5, a16);
    gsl_matrix_set(m_, 1, 0, a12);
    gsl_matrix_set(m_, 1, 1, a22);
    gsl_matrix_set(m_, 1, 2, a23);
    gsl_matrix_set(m_, 1, 3, a24);
    gsl_matrix_set(m_, 1, 4, a25);
    gsl_matrix_set(m_, 1, 5, a26);
    gsl_matrix_set(m_, 2, 0, a13);
    gsl_matrix_set(m_, 2, 1, a23);
    gsl_matrix_set(m_, 2, 2, a33);
    gsl_matrix_set(m_, 2, 3, a34);
    gsl_matrix_set(m_, 2, 4, a35);
    gsl_matrix_set(m_, 2, 5, a36);
    gsl_matrix_set(m_, 3, 0, a14);
    gsl_matrix_set(m_, 3, 1, a24);
    gsl_matrix_set(m_, 3, 2, a34);
    gsl_matrix_set(m_, 3, 3, a44);
    gsl_matrix_set(m_, 3, 4, a45);
    gsl_matrix_set(m_, 3, 5, a46);
    gsl_matrix_set(m_, 4, 0, a15);
    gsl_matrix_set(m_, 4, 1, a25);
    gsl_matrix_set(m_, 4, 2, a35);
    gsl_matrix_set(m_, 4, 3, a45);
    gsl_matrix_set(m_, 4, 4, a55);
    gsl_matrix_set(m_, 4, 5, a56);
    gsl_matrix_set(m_, 5, 0, a16);
    gsl_matrix_set(m_, 5, 1, a26);
    gsl_matrix_set(m_, 5, 2, a36);
    gsl_matrix_set(m_, 5, 3, a46);
    gsl_matrix_set(m_, 5, 4, a56);
    gsl_matrix_set(m_, 5, 5, a66);

    dfdt_[0] = 0.0;
    dfdt_[1] = 0.0;
    dfdt_[2] = 0.0;
    dfdt_[3] = 0.0;
    dfdt_[4] = 0.0;
    dfdt_[5] = 0.0;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian with respect to the parameters.
 */

int LinearSystem_jacp(double t, const double y_[], double *jacp_, void *params)
{
    const double a11 = -6.0999999999999996e+00;
    const double a12 = 1.8999999999999999e+00;
    const double a13 = -1.8000000000000000e+00;
    const double a14 = -2.0000000000000001e-01;
    const double a15 = 9.0000000000000002e-01;
    const double a16 = -4.7999999999999998e+00;
    const double a22 = -2.8999999999999999e+00;
    const double a23 = 1.0;
    const double a24 = 2.9999999999999999e-01;
    const double a25 = 2.7000000000000002e+00;
    const double a26 = 9.0000000000000002e-01;
    const double a33 = -4.2999999999999998e+00;
    const double a34 = 1.2000000000000000e+00;
    const double a35 = -2.2000000000000002e+00;
    const double a36 = 1.3000000000000000e+00;
    const double a44 = -4.9000000000000004e+00;
    const double a45 = -6.9999999999999996e-01;
    const double a46 = -3.7000000000000002e+00;
    const double a55 = -6.4000000000000004e+00;
    const double a56 = 1.1000000000000001e+00;
    const double a66 = -1.0600000000000000e+01;
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];

    gsl_matrix_view dfdp_mat = gsl_matrix_view_array(jacp_,6,7);
    gsl_matrix *m_ = &dfdp_mat.matrix;

    gsl_matrix_set(m_, 0, 0, 2.0*b1);
    gsl_matrix_set(m_, 0, 1, 0.0);
    gsl_matrix_set(m_, 0, 2, 0.0);
    gsl_matrix_set(m_, 0, 3, 0.0);
    gsl_matrix_set(m_, 0, 4, 0.0);
    gsl_matrix_set(m_, 0, 5, 0.0);
    gsl_matrix_set(m_, 0, 6, 1.0);
    gsl_matrix_set(m_, 1, 0, 0.0);
    gsl_matrix_set(m_, 1, 1, 2.0*b2);
    gsl_matrix_set(m_, 1, 2, 0.0);
    gsl_matrix_set(m_, 1, 3, 0.0);
    gsl_matrix_set(m_, 1, 4, 0.0);
    gsl_matrix_set(m_, 1, 5, 0.0);
    gsl_matrix_set(m_, 1, 6, 1.0);
    gsl_matrix_set(m_, 2, 0, 0.0);
    gsl_matrix_set(m_, 2, 1, 0.0);
    gsl_matrix_set(m_, 2, 2, 2.0*b3);
    gsl_matrix_set(m_, 2, 3, 0.0);
    gsl_matrix_set(m_, 2, 4, 0.0);
    gsl_matrix_set(m_, 2, 5, 0.0);
    gsl_matrix_set(m_, 2, 6, 1.0);
    gsl_matrix_set(m_, 3, 0, 0.0);
    gsl_matrix_set(m_, 3, 1, 0.0);
    gsl_matrix_set(m_, 3, 2, 0.0);
    gsl_matrix_set(m_, 3, 3, 2.0*b4);
    gsl_matrix_set(m_, 3, 4, 0.0);
    gsl_matrix_set(m_, 3, 5, 0.0);
    gsl_matrix_set(m_, 3, 6, 1.0);
    gsl_matrix_set(m_, 4, 0, 0.0);
    gsl_matrix_set(m_, 4, 1, 0.0);
    gsl_matrix_set(m_, 4, 2, 0.0);
    gsl_matrix_set(m_, 4, 3, 0.0);
    gsl_matrix_set(m_, 4, 4, 2.0*b5);
    gsl_matrix_set(m_, 4, 5, 0.0);
    gsl_matrix_set(m_, 4, 6, 1.0);
    gsl_matrix_set(m_, 5, 0, 0.0);
    gsl_matrix_set(m_, 5, 1, 0.0);
    gsl_matrix_set(m_, 5, 2, 0.0);
    gsl_matrix_set(m_, 5, 3, 0.0);
    gsl_matrix_set(m_, 5, 4, 0.0);
    gsl_matrix_set(m_, 5, 5, 2.0*b6);
    gsl_matrix_set(m_, 5, 6, 1.0);

    return GSL_SUCCESS;
}
