/*
 *  LinearSystem_gvf.c
 *
 *  GSL C file for the vector field named: LinearSystem
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 26-Apr-2021 at 01:27
 */

#include <math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_odeiv.h>

/*
 *  The vector field.
 */

int LinearSystem_vf(double t, const double y_[], double f_[], void *params)
{
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u, a11, a12, a13, a14, a15, a16, a22, a23, a24, a25, a26, a33, a34, a35, a36, a44, a45, a46, a55, a56, a66;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];
    a11        = p_[7];
    a12        = p_[8];
    a13        = p_[9];
    a14        = p_[10];
    a15        = p_[11];
    a16        = p_[12];
    a22        = p_[13];
    a23        = p_[14];
    a24        = p_[15];
    a25        = p_[16];
    a26        = p_[17];
    a33        = p_[18];
    a34        = p_[19];
    a35        = p_[20];
    a36        = p_[21];
    a44        = p_[22];
    a45        = p_[23];
    a46        = p_[24];
    a55        = p_[25];
    a56        = p_[26];
    a66        = p_[27];

    f_[0] =  a16*x6+a14*x4+a13*x3+a15*x5+a12*x2+x1*a11;
    f_[1] =  x4*a24+a26*x6+a25*x5+x1*a12+a23*x3+a22*x2;
    f_[2] =  a23*x2+x1*a13+a36*x6+a35*x5+a33*x3+x4*a34;
    f_[3] =  x3*a34+x4*a44+x2*a24+a45*x5+x1*a14+a46*x6;
    f_[4] =  a56*x6+a45*x4+x1*a15+a25*x2+a35*x3+x5*a55;
    f_[5] =  a36*x3+a56*x5+x1*a16+a66*x6+x4*a46+a26*x2;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian.
 */

int LinearSystem_jac(double t, const double y_[], double *jac_, double *dfdt_, void *params)
{
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u, a11, a12, a13, a14, a15, a16, a22, a23, a24, a25, a26, a33, a34, a35, a36, a44, a45, a46, a55, a56, a66;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];
    a11        = p_[7];
    a12        = p_[8];
    a13        = p_[9];
    a14        = p_[10];
    a15        = p_[11];
    a16        = p_[12];
    a22        = p_[13];
    a23        = p_[14];
    a24        = p_[15];
    a25        = p_[16];
    a26        = p_[17];
    a33        = p_[18];
    a34        = p_[19];
    a35        = p_[20];
    a36        = p_[21];
    a44        = p_[22];
    a45        = p_[23];
    a46        = p_[24];
    a55        = p_[25];
    a56        = p_[26];
    a66        = p_[27];

    gsl_matrix_view dfdy_mat = gsl_matrix_view_array(jac_,6,6);
    gsl_matrix *m_ = &dfdy_mat.matrix;

    gsl_matrix_set(m_, 0, 0, a11);
    gsl_matrix_set(m_, 0, 1, a12);
    gsl_matrix_set(m_, 0, 2, a13);
    gsl_matrix_set(m_, 0, 3, a14);
    gsl_matrix_set(m_, 0, 4, a15);
    gsl_matrix_set(m_, 0, 5, a16);
    gsl_matrix_set(m_, 1, 0, a12);
    gsl_matrix_set(m_, 1, 1, a22);
    gsl_matrix_set(m_, 1, 2, a23);
    gsl_matrix_set(m_, 1, 3, a24);
    gsl_matrix_set(m_, 1, 4, a25);
    gsl_matrix_set(m_, 1, 5, a26);
    gsl_matrix_set(m_, 2, 0, a13);
    gsl_matrix_set(m_, 2, 1, a23);
    gsl_matrix_set(m_, 2, 2, a33);
    gsl_matrix_set(m_, 2, 3, a34);
    gsl_matrix_set(m_, 2, 4, a35);
    gsl_matrix_set(m_, 2, 5, a36);
    gsl_matrix_set(m_, 3, 0, a14);
    gsl_matrix_set(m_, 3, 1, a24);
    gsl_matrix_set(m_, 3, 2, a34);
    gsl_matrix_set(m_, 3, 3, a44);
    gsl_matrix_set(m_, 3, 4, a45);
    gsl_matrix_set(m_, 3, 5, a46);
    gsl_matrix_set(m_, 4, 0, a15);
    gsl_matrix_set(m_, 4, 1, a25);
    gsl_matrix_set(m_, 4, 2, a35);
    gsl_matrix_set(m_, 4, 3, a45);
    gsl_matrix_set(m_, 4, 4, a55);
    gsl_matrix_set(m_, 4, 5, a56);
    gsl_matrix_set(m_, 5, 0, a16);
    gsl_matrix_set(m_, 5, 1, a26);
    gsl_matrix_set(m_, 5, 2, a36);
    gsl_matrix_set(m_, 5, 3, a46);
    gsl_matrix_set(m_, 5, 4, a56);
    gsl_matrix_set(m_, 5, 5, a66);

    dfdt_[0] = 0.0;
    dfdt_[1] = 0.0;
    dfdt_[2] = 0.0;
    dfdt_[3] = 0.0;
    dfdt_[4] = 0.0;
    dfdt_[5] = 0.0;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian with respect to the parameters.
 */

int LinearSystem_jacp(double t, const double y_[], double *jacp_, void *params)
{
    double x1, x2, x3, x4, x5, x6;
    double b1, b2, b3, b4, b5, b6, u, a11, a12, a13, a14, a15, a16, a22, a23, a24, a25, a26, a33, a34, a35, a36, a44, a45, a46, a55, a56, a66;
    double *p_;

    p_ = (double *) params;

    x1         = y_[0];
    x2         = y_[1];
    x3         = y_[2];
    x4         = y_[3];
    x5         = y_[4];
    x6         = y_[5];

    b1         = p_[0];
    b2         = p_[1];
    b3         = p_[2];
    b4         = p_[3];
    b5         = p_[4];
    b6         = p_[5];
    u          = p_[6];
    a11        = p_[7];
    a12        = p_[8];
    a13        = p_[9];
    a14        = p_[10];
    a15        = p_[11];
    a16        = p_[12];
    a22        = p_[13];
    a23        = p_[14];
    a24        = p_[15];
    a25        = p_[16];
    a26        = p_[17];
    a33        = p_[18];
    a34        = p_[19];
    a35        = p_[20];
    a36        = p_[21];
    a44        = p_[22];
    a45        = p_[23];
    a46        = p_[24];
    a55        = p_[25];
    a56        = p_[26];
    a66        = p_[27];

    gsl_matrix_view dfdp_mat = gsl_matrix_view_array(jacp_,6,28);
    gsl_matrix *m_ = &dfdp_mat.matrix;

    gsl_matrix_set(m_, 0, 0, 0.0);
    gsl_matrix_set(m_, 0, 1, 0.0);
    gsl_matrix_set(m_, 0, 2, 0.0);
    gsl_matrix_set(m_, 0, 3, 0.0);
    gsl_matrix_set(m_, 0, 4, 0.0);
    gsl_matrix_set(m_, 0, 5, 0.0);
    gsl_matrix_set(m_, 0, 6, 0.0);
    gsl_matrix_set(m_, 0, 7, x1);
    gsl_matrix_set(m_, 0, 8, x2);
    gsl_matrix_set(m_, 0, 9, x3);
    gsl_matrix_set(m_, 0, 10, x4);
    gsl_matrix_set(m_, 0, 11, x5);
    gsl_matrix_set(m_, 0, 12, x6);
    gsl_matrix_set(m_, 0, 13, 0.0);
    gsl_matrix_set(m_, 0, 14, 0.0);
    gsl_matrix_set(m_, 0, 15, 0.0);
    gsl_matrix_set(m_, 0, 16, 0.0);
    gsl_matrix_set(m_, 0, 17, 0.0);
    gsl_matrix_set(m_, 0, 18, 0.0);
    gsl_matrix_set(m_, 0, 19, 0.0);
    gsl_matrix_set(m_, 0, 20, 0.0);
    gsl_matrix_set(m_, 0, 21, 0.0);
    gsl_matrix_set(m_, 0, 22, 0.0);
    gsl_matrix_set(m_, 0, 23, 0.0);
    gsl_matrix_set(m_, 0, 24, 0.0);
    gsl_matrix_set(m_, 0, 25, 0.0);
    gsl_matrix_set(m_, 0, 26, 0.0);
    gsl_matrix_set(m_, 0, 27, 0.0);
    gsl_matrix_set(m_, 1, 0, 0.0);
    gsl_matrix_set(m_, 1, 1, 0.0);
    gsl_matrix_set(m_, 1, 2, 0.0);
    gsl_matrix_set(m_, 1, 3, 0.0);
    gsl_matrix_set(m_, 1, 4, 0.0);
    gsl_matrix_set(m_, 1, 5, 0.0);
    gsl_matrix_set(m_, 1, 6, 0.0);
    gsl_matrix_set(m_, 1, 7, 0.0);
    gsl_matrix_set(m_, 1, 8, x1);
    gsl_matrix_set(m_, 1, 9, 0.0);
    gsl_matrix_set(m_, 1, 10, 0.0);
    gsl_matrix_set(m_, 1, 11, 0.0);
    gsl_matrix_set(m_, 1, 12, 0.0);
    gsl_matrix_set(m_, 1, 13, x2);
    gsl_matrix_set(m_, 1, 14, x3);
    gsl_matrix_set(m_, 1, 15, x4);
    gsl_matrix_set(m_, 1, 16, x5);
    gsl_matrix_set(m_, 1, 17, x6);
    gsl_matrix_set(m_, 1, 18, 0.0);
    gsl_matrix_set(m_, 1, 19, 0.0);
    gsl_matrix_set(m_, 1, 20, 0.0);
    gsl_matrix_set(m_, 1, 21, 0.0);
    gsl_matrix_set(m_, 1, 22, 0.0);
    gsl_matrix_set(m_, 1, 23, 0.0);
    gsl_matrix_set(m_, 1, 24, 0.0);
    gsl_matrix_set(m_, 1, 25, 0.0);
    gsl_matrix_set(m_, 1, 26, 0.0);
    gsl_matrix_set(m_, 1, 27, 0.0);
    gsl_matrix_set(m_, 2, 0, 0.0);
    gsl_matrix_set(m_, 2, 1, 0.0);
    gsl_matrix_set(m_, 2, 2, 0.0);
    gsl_matrix_set(m_, 2, 3, 0.0);
    gsl_matrix_set(m_, 2, 4, 0.0);
    gsl_matrix_set(m_, 2, 5, 0.0);
    gsl_matrix_set(m_, 2, 6, 0.0);
    gsl_matrix_set(m_, 2, 7, 0.0);
    gsl_matrix_set(m_, 2, 8, 0.0);
    gsl_matrix_set(m_, 2, 9, x1);
    gsl_matrix_set(m_, 2, 10, 0.0);
    gsl_matrix_set(m_, 2, 11, 0.0);
    gsl_matrix_set(m_, 2, 12, 0.0);
    gsl_matrix_set(m_, 2, 13, 0.0);
    gsl_matrix_set(m_, 2, 14, x2);
    gsl_matrix_set(m_, 2, 15, 0.0);
    gsl_matrix_set(m_, 2, 16, 0.0);
    gsl_matrix_set(m_, 2, 17, 0.0);
    gsl_matrix_set(m_, 2, 18, x3);
    gsl_matrix_set(m_, 2, 19, x4);
    gsl_matrix_set(m_, 2, 20, x5);
    gsl_matrix_set(m_, 2, 21, x6);
    gsl_matrix_set(m_, 2, 22, 0.0);
    gsl_matrix_set(m_, 2, 23, 0.0);
    gsl_matrix_set(m_, 2, 24, 0.0);
    gsl_matrix_set(m_, 2, 25, 0.0);
    gsl_matrix_set(m_, 2, 26, 0.0);
    gsl_matrix_set(m_, 2, 27, 0.0);
    gsl_matrix_set(m_, 3, 0, 0.0);
    gsl_matrix_set(m_, 3, 1, 0.0);
    gsl_matrix_set(m_, 3, 2, 0.0);
    gsl_matrix_set(m_, 3, 3, 0.0);
    gsl_matrix_set(m_, 3, 4, 0.0);
    gsl_matrix_set(m_, 3, 5, 0.0);
    gsl_matrix_set(m_, 3, 6, 0.0);
    gsl_matrix_set(m_, 3, 7, 0.0);
    gsl_matrix_set(m_, 3, 8, 0.0);
    gsl_matrix_set(m_, 3, 9, 0.0);
    gsl_matrix_set(m_, 3, 10, x1);
    gsl_matrix_set(m_, 3, 11, 0.0);
    gsl_matrix_set(m_, 3, 12, 0.0);
    gsl_matrix_set(m_, 3, 13, 0.0);
    gsl_matrix_set(m_, 3, 14, 0.0);
    gsl_matrix_set(m_, 3, 15, x2);
    gsl_matrix_set(m_, 3, 16, 0.0);
    gsl_matrix_set(m_, 3, 17, 0.0);
    gsl_matrix_set(m_, 3, 18, 0.0);
    gsl_matrix_set(m_, 3, 19, x3);
    gsl_matrix_set(m_, 3, 20, 0.0);
    gsl_matrix_set(m_, 3, 21, 0.0);
    gsl_matrix_set(m_, 3, 22, x4);
    gsl_matrix_set(m_, 3, 23, x5);
    gsl_matrix_set(m_, 3, 24, x6);
    gsl_matrix_set(m_, 3, 25, 0.0);
    gsl_matrix_set(m_, 3, 26, 0.0);
    gsl_matrix_set(m_, 3, 27, 0.0);
    gsl_matrix_set(m_, 4, 0, 0.0);
    gsl_matrix_set(m_, 4, 1, 0.0);
    gsl_matrix_set(m_, 4, 2, 0.0);
    gsl_matrix_set(m_, 4, 3, 0.0);
    gsl_matrix_set(m_, 4, 4, 0.0);
    gsl_matrix_set(m_, 4, 5, 0.0);
    gsl_matrix_set(m_, 4, 6, 0.0);
    gsl_matrix_set(m_, 4, 7, 0.0);
    gsl_matrix_set(m_, 4, 8, 0.0);
    gsl_matrix_set(m_, 4, 9, 0.0);
    gsl_matrix_set(m_, 4, 10, 0.0);
    gsl_matrix_set(m_, 4, 11, x1);
    gsl_matrix_set(m_, 4, 12, 0.0);
    gsl_matrix_set(m_, 4, 13, 0.0);
    gsl_matrix_set(m_, 4, 14, 0.0);
    gsl_matrix_set(m_, 4, 15, 0.0);
    gsl_matrix_set(m_, 4, 16, x2);
    gsl_matrix_set(m_, 4, 17, 0.0);
    gsl_matrix_set(m_, 4, 18, 0.0);
    gsl_matrix_set(m_, 4, 19, 0.0);
    gsl_matrix_set(m_, 4, 20, x3);
    gsl_matrix_set(m_, 4, 21, 0.0);
    gsl_matrix_set(m_, 4, 22, 0.0);
    gsl_matrix_set(m_, 4, 23, x4);
    gsl_matrix_set(m_, 4, 24, 0.0);
    gsl_matrix_set(m_, 4, 25, x5);
    gsl_matrix_set(m_, 4, 26, x6);
    gsl_matrix_set(m_, 4, 27, 0.0);
    gsl_matrix_set(m_, 5, 0, 0.0);
    gsl_matrix_set(m_, 5, 1, 0.0);
    gsl_matrix_set(m_, 5, 2, 0.0);
    gsl_matrix_set(m_, 5, 3, 0.0);
    gsl_matrix_set(m_, 5, 4, 0.0);
    gsl_matrix_set(m_, 5, 5, 0.0);
    gsl_matrix_set(m_, 5, 6, 0.0);
    gsl_matrix_set(m_, 5, 7, 0.0);
    gsl_matrix_set(m_, 5, 8, 0.0);
    gsl_matrix_set(m_, 5, 9, 0.0);
    gsl_matrix_set(m_, 5, 10, 0.0);
    gsl_matrix_set(m_, 5, 11, 0.0);
    gsl_matrix_set(m_, 5, 12, x1);
    gsl_matrix_set(m_, 5, 13, 0.0);
    gsl_matrix_set(m_, 5, 14, 0.0);
    gsl_matrix_set(m_, 5, 15, 0.0);
    gsl_matrix_set(m_, 5, 16, 0.0);
    gsl_matrix_set(m_, 5, 17, x2);
    gsl_matrix_set(m_, 5, 18, 0.0);
    gsl_matrix_set(m_, 5, 19, 0.0);
    gsl_matrix_set(m_, 5, 20, 0.0);
    gsl_matrix_set(m_, 5, 21, x3);
    gsl_matrix_set(m_, 5, 22, 0.0);
    gsl_matrix_set(m_, 5, 23, 0.0);
    gsl_matrix_set(m_, 5, 24, x4);
    gsl_matrix_set(m_, 5, 25, 0.0);
    gsl_matrix_set(m_, 5, 26, x5);
    gsl_matrix_set(m_, 5, 27, x6);

    return GSL_SUCCESS;
}
